# -*- coding: utf-8 -*-
"""Sign_language_Finalipynb.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d5Dr-evHsGc4dOKyFsDQGLQ-NzDbl7et
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.cluster import KMeans

train = pd.read_csv("/content/sign_mnist_train.csv")
test = pd.read_csv("/content/sign_mnist_test.csv")

print(train.shape)
train.head()

X = train.drop("label", axis=1)
y = train["label"]
X = X / 255.0
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2)

"""# Visualize Data"""

plt.imshow(X.iloc[0].values.reshape(28,28), cmap='hot')
plt.title(f"Label: {y.iloc[0]}")
plt.show()

"""# Train ML Models

1. Logistic Regression
"""

lr = LogisticRegression(max_iter=1000)
lr.fit(X_train, y_train)

y_pred_lr = lr.predict(X_val)
print("LR Accuracy:", accuracy_score(y_val, y_pred_lr))

"""2. Support Vector Machine (SVM)"""

svm = SVC()
svm.fit(X_train, y_train)

y_pred_svm = svm.predict(X_val)
print("SVM Accuracy:", accuracy_score(y_val, y_pred_svm))

"""3. Decision Tree"""

dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)

y_pred_dt = dt.predict(X_val)
print("DT Accuracy:", accuracy_score(y_val, y_pred_dt))

"""4. Random Forest"""

rf = RandomForestClassifier(n_estimators=100)
rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_val)
print("RF Accuracy:", accuracy_score(y_val, y_pred_rf))

"""5. K-Means (Unsupervised)"""

kmeans = KMeans(n_clusters=24)
kmeans.fit(X_train)

y_pred_kmeans = kmeans.labels_
print("KMeans done (unsupervised)")

import seaborn as sns

cm = confusion_matrix(y_val, y_pred_rf)
sns.heatmap(cm, annot=False)
plt.title("Confusion Matrix")
plt.show()

models = ["LR", "SVM", "DT", "RF"]
accuracies = [
    accuracy_score(y_val, y_pred_lr),
    accuracy_score(y_val, y_pred_svm),
    accuracy_score(y_val, y_pred_dt),
    accuracy_score(y_val, y_pred_rf)
]

plt.bar(models, accuracies)
plt.title("Model Comparison")
plt.xlabel("Models")
plt.ylabel("Accuracy")
plt.show()

"""# Final Prediction"""

test_X = test.drop("label", axis=1) / 255.0
test_y = test["label"]

final_pred = rf.predict(test_X)

print("Final Test Accuracy:", accuracy_score(test_y, final_pred))

import joblib
joblib.dump(rf, "sign_language_model.pkl")

"""# XGBOOST"""

pip install xgboost

from xgboost import XGBClassifier

X = train.drop("label", axis=1).values   # convert to NumPy directly
y = train["label"].values

X = X / 255.0

X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.2, random_state=42
)

le = LabelEncoder()

y_train = le.fit_transform(y_train)
y_val = le.transform(y_val)

xgb = XGBClassifier(
    n_estimators=20,
    max_depth=3,
    learning_rate=0.3,
    n_jobs=-1,
    objective='multi:softmax',
    num_class=24
)

xgb.fit(X_train, y_train)

from xgboost import XGBClassifier

xgb = XGBClassifier(
    n_estimators=30,
    learning_rate=0.2,
    max_depth=4,
    subsample=0.8,
    colsample_bytree=0.8,
    tree_method='hist',
    n_jobs=-1,
    objective='multi:softprob',
    num_class=24,
    eval_metric='mlogloss'
)

# Train on smaller data for speed
xgb.fit(X_train[:5000], y_train[:5000])

y_pred = xgb.predict(X_val)

print("Accuracy:", accuracy_score(y_val, y_pred))

print(classification_report(y_val, y_pred))

cm = confusion_matrix(y_val, y_pred)
plt.imshow(cm)
plt.title("Confusion Matrix - XGBoost")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.colorbar()
plt.show()

X_test = test.drop("label", axis=1).values / 255.0
y_test = test["label"].values

# Apply same label encoder
y_test = le.transform(y_test)

y_test_pred = xgb.predict(X_test)

print("Test Accuracy:", accuracy_score(y_test, y_test_pred))

"""# STATS"""

X_small = X_train[:3000]
y_small = y_train[:3000]

scores = cross_val_score(svm, X_small, y_small, cv=3)

print(scores.mean())

from sklearn.decomposition import PCA

pca = PCA(n_components=100)
X_train_pca = pca.fit_transform(X_train)
X_val_pca = pca.transform(X_val)

param_grid = {
    'max_depth': [3],
    'n_estimators': [10]
}

grid = GridSearchCV(xgb, param_grid, cv=2)

grid.fit(X_train[:3000], y_train[:3000])

from sklearn.metrics import roc_auc_score

from sklearn.metrics import roc_curve, auc
from sklearn.preprocessing import label_binarize
import matplotlib.pyplot as plt
import numpy as np

# Convert labels to one-hot (multi-class → binary)
classes = np.unique(y_val)

y_val_bin = label_binarize(y_val, classes=classes)

from xgboost import XGBClassifier

xgb = XGBClassifier(
    n_estimators=10,
    max_depth=3,
    learning_rate=0.3,
    tree_method='hist',
    n_jobs=-1,
    objective='multi:softprob',
    num_class=24
)
# Train on small data (fast)
xgb.fit(X_train[:5000], y_train[:5000])

from sklearn.metrics import roc_curve, auc
import matplotlib.pyplot as plt

# Use only 1 class for fast plotting
fpr, tpr, _ = roc_curve(y_val_bin[:, 0], y_score[:, 0])
roc_auc = auc(fpr, tpr)

plt.figure()
plt.plot(fpr, tpr, label=f"AUC = {roc_auc:.2f}")
plt.plot([0, 1], [0, 1], 'k--')  # random line

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve with AUC (XGBoost)")
plt.legend()
plt.show()

"""# FINAL PIPELINE (SVM + XGBoost + Stats + ROC + AUC)"""

X_train_small = X_train[:5000]
y_train_small = y_train[:5000]

X_val_small = X_val[:1000]
y_val_small = y_val[:1000]

from sklearn.svm import LinearSVC

svm = LinearSVC(max_iter=2000)
svm.fit(X_train_small, y_train_small)

y_pred_svm = svm.predict(X_val_small)

from xgboost import XGBClassifier

xgb = XGBClassifier(
    n_estimators=30,
    max_depth=4,
    learning_rate=0.2,
    tree_method='hist',
    n_jobs=-1,
    objective='multi:softprob',
    num_class=24
)

xgb.fit(X_train_small, y_train_small)

y_pred_xgb = xgb.predict(X_val_small)

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# SVM
svm_acc = accuracy_score(y_val_small, y_pred_svm)
svm_prec = precision_score(y_val_small, y_pred_svm, average='weighted')
svm_rec = recall_score(y_val_small, y_pred_svm, average='weighted')
svm_f1 = f1_score(y_val_small, y_pred_svm, average='weighted')

# XGBoost
xgb_acc = accuracy_score(y_val_small, y_pred_xgb)
xgb_prec = precision_score(y_val_small, y_pred_xgb, average='weighted')
xgb_rec = recall_score(y_val_small, y_pred_xgb, average='weighted')
xgb_f1 = f1_score(y_val_small, y_pred_xgb, average='weighted')

import pandas as pd

results = pd.DataFrame({
    "Metric": ["Accuracy", "Precision", "Recall", "F1 Score"],
    "SVM": [svm_acc, svm_prec, svm_rec, svm_f1],
    "XGBoost": [xgb_acc, xgb_prec, xgb_rec, xgb_f1]
})

print(results)

from sklearn.preprocessing import label_binarize
from sklearn.metrics import roc_auc_score
import numpy as np

y_score = xgb.predict_proba(X_val_small)

classes = np.unique(y_val_small)
y_val_bin = label_binarize(y_val_small, classes=classes)

auc_score = roc_auc_score(y_val_bin, y_score, multi_class='ovr')

print("AUC Score (XGBoost):", auc_score)

from sklearn.metrics import roc_curve, auc
import matplotlib.pyplot as plt

# Use 1 class (fast)
fpr, tpr, _ = roc_curve(y_val_bin[:, 0], y_score[:, 0])
roc_auc = auc(fpr, tpr)

plt.figure()
plt.plot(fpr, tpr, label=f"AUC = {roc_auc:.2f}")
plt.plot([0, 1], [0, 1], 'k--')

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve - XGBoost")
plt.legend()
plt.show()

models = ["Before Tuning", "After Tuning"]
accuracy = [0.85, 0.93]

plt.bar(models, accuracy)
plt.title("Model Improvement")
plt.show()

from xgboost import plot_importance

plot_importance(xgb)
plt.show()